version: "3.8"
services:
  # MongoDB service
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongodb.env
    networks:
      - private

  # Backend - Express service
  babble-backend:
    build:
      context: ./babble-backend
      dockerfile: Dockerfile
    container_name: babble-backend
    ports:
      - "8080:8080"
    volumes:
      - ./babble-backend:/app/babble-backend
      - /app/babble-backend/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    networks:
      - private

  # React - Frontend service
  babble-frontend:
    build:
      context: ./babble-frontend
      dockerfile: Dockerfile
    container_name: babble-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./babble-frontend:/app/babble-frontend
      - /app/babble-frontend/node_modules
    networks:
      - private

networks:
  private:
    driver: bridge

# we are specifying explicitly to docker compose, that this is an named volume.
volumes:
  data:
